// <auto-generated />
namespace MoodTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedActivityAndActivityLogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedActivityAndActivityLogs));
        
        string IMigrationMetadata.Id
        {
            get { return "201906120445138_AddedActivityAndActivityLogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
